### ISSUE TITLE
Events - Briefcase - In case of no events yet, display a message for no events instead of the empty table

### ISSUE THREAD

**Issue by nsbedair** [IBM-FEPS-Org/IBM-FEPS-Rep#10]
![image](https://user-images.githubusercontent.com/32294462/34032196-8e18a66a-e17d-11e7-96d9-a69ae9f9fc92.png)

**Comment by nsbedair** [comment]
![image](https://user-images.githubusercontent.com/32294462/34424083-7be18488-ec29-11e7-8426-071f4a1e47f3.png)

**Comment by nsbedair** [comment]
Events section is completely empty, I expected a message that user is not registered to events yet

**Comment by NadaEmad12** [comment]
<img width="1027" alt="untitled" src="https://user-images.githubusercontent.com/33512767/34437861-af947548-ecaa-11e7-83fb-8c8f0ecffd18.png">

I did this already, but I'll check it again

**Comment by nsbedair** [comment]
fixed
