### ISSUE TITLE
Event - Notification mail - Message should consider the user's gender

### ISSUE THREAD

**Issue by nsbedair** [IBM-FEPS-Org/IBM-FEPS-Rep#8]
![image](https://user-images.githubusercontent.com/32294462/34031154-b88b6838-e178-11e7-97c5-e5152515033a.png)
![image](https://user-images.githubusercontent.com/32294462/34031163-bd020eda-e178-11e7-9b51-9ea4b5259515.png)
Also the rejection message should be changed

**Comment by NadaEmad12** [comment]
I changed this, but generally we'll change all the email templates.

**Comment by nsbedair** [comment]
fixed, thank you
